name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  weights_path: https://github.com/suborofu/background-remover/releases/download/v${{ vars.LAST_RELEASE_VERSION }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Keep only demo
        run: |
          cd ${{ github.workspace }}/..
          mv ${{ github.workspace }}/demo .
          rm -rf ${{ github.workspace }}
          mv ./demo ${{ github.workspace }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ github.workspace }}/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - name: Download model files
        run: |
          mkdir ./model_weights
          cd ./model_weights
          wget $weights_path/model.onnx
          wget $weights_path/model.json
          wget $weights_path/group1-shard1of1.bin
      - name: Build
        run: npx next build
      - name: Jekyll bypass
        run: touch ./build/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
