name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Keep only demo
        run: mv ${{ github.workspace }}/demo ${{ github.workspace }}/.. && rm -rf ${{ github.workspace }} && mv ${{ github.workspace }}/../demo ${{ github.workspace }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ github.workspace }}/package-lock.json
      - name: Install dependencies
        run: cd ${{ github.workspace }} && npm ci
      - name: Build
        run: cd ${{ github.workspace }} && npm run build
