name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ github.workspace }}/demo/package-lock.json
      - name: Install dependencies
        run: cd ${{ github.workspace }}/demo && npm ci
      - name: Build
        run: cd ${{ github.workspace }}/demo && npm run build
      - name: Start
        run: cd ${{ github.workspace }}/demo && npm run start
