name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Keep only demo
        run: |
          cd ${{ github.workspace }}/..
          mv ${{ github.workspace }}/demo .
          rm -rf ${{ github.workspace }}
          mv ./demo ${{ github.workspace }} 
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ github.workspace }}/package-lock.json
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: cd ${{ github.workspace }} && npm ci
      - name: Build
        run: cd ${{ github.workspace }} && npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
